name: syg_materiales_flutter
description: "Sistema de gestiÃ³n de materiales S&G"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Utils
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  intl: ^0.20.2
  google_fonts: ^6.1.0
  equatable: ^2.0.5

  # Archivos y PDF
  pdf: ^3.10.4
  printing: ^5.11.0
  excel: ^4.0.0
  path_provider: ^2.1.2
  share_plus: ^12.0.1

  # Base de Datos Local
  sqflite: ^2.3.0
  path: ^1.8.3

  # ðŸ”¥ FIREBASE (Versiones Compatibles)
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4

  # Notificaciones Locales
  flutter_local_notifications: ^19.5.0
  firebase_storage: ^13.0.4
  signature: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ConfiguraciÃ³n de Iconos
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "web/icons/Logo_SYG.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "web/icons/Logo_SYG.png"
    background_color: "#0175C2"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "web/icons/Logo_SYG.png"
    icon_size: 48

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg